name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repos
        uses: action/checkout@v3

      - name: Setup Nodejs
        uses: action/setup-nodejs@v3

      - name: Install dependencies
        run: make install

      - name: Make lint
        run: make lint